# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ChangelogPr < Formula
  desc "CLI tool for building changelog from PR descriptions based on a template"
  homepage "https://github.com/splicemachine/changelog-pr/"
  version "0.1.1"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/splicemachine/changelog-pr/releases/download/v0.1.1/changelog-pr_darwin_amd64.tar.gz"
    sha256 "4a208a21fc3dd41c51a523f49f009c9eb9d2845da92b22a20949ad870b58164d"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/splicemachine/changelog-pr/releases/download/v0.1.1/changelog-pr_linux_amd64.tar.gz"
    sha256 "365f2e580afa97c4a26864447ab85c612e92adb9ccc3eb4d2ad121de4276c497"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/splicemachine/changelog-pr/releases/download/v0.1.1/changelog-pr_linux_arm64.tar.gz"
    sha256 "2b6894d1f2c7e2e3b9af892d7cd92d8993be4f52fae9997335df6ac2c8ef3452"
  end

  def install
    bin.install "changelog-pr"
  end

  test do
    system "#{bin}/changelog-pr --help"
  end
end
