# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Splicectl < Formula
  desc "This is the control CLI for Splice Machine databases on Kubernetes"
  homepage "https://github.com/splicemachine/splicectl/"
  version "0.1.1"
  license "AGPL-3.0-only"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/splicemachine/splicectl/releases/download/v0.1.1/splicectl_darwin_amd64.tar.gz"
    sha256 "e18c516b868fb5198487446ad43ce8d95a5e251f744347755cfc465ff435fd0a"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/splicemachine/splicectl/releases/download/v0.1.1/splicectl_linux_amd64.tar.gz"
    sha256 "eca5d0aa816faa69f8b9415319c19306c7256631952b2927b70a2ee8cfc92b3e"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/splicemachine/splicectl/releases/download/v0.1.1/splicectl_linux_arm64.tar.gz"
    sha256 "77247132a9a1c9be6c0d9cdf7b1dc50b29e3ad8faec310a23fb2f4aae235e9b3"
  end

  def install
    bin.install "splicectl"
  end

  test do
    system "#{bin}/splicectl --help"
  end
end
