# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Splicectl < Formula
  desc "This is the control CLI for Splice Machine databases on Kubernetes"
  homepage "https://github.com/splicemachine/splicectl/"
  version "0.1.0"
  license "AGPL-3.0-only"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/splicemachine/splicectl/releases/download/v0.1.0/splicectl_darwin_amd64.tar.gz"
    sha256 "e6cd808e322fddd5f2f4291133fe097eb0a0b8f818a50467f35bd62c7f20f999"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/splicemachine/splicectl/releases/download/v0.1.0/splicectl_linux_amd64.tar.gz"
    sha256 "8b344ffb866b2f596f1d6927b827a02e802dcf23589bac3f630d3507ffd19bb4"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/splicemachine/splicectl/releases/download/v0.1.0/splicectl_linux_arm64.tar.gz"
    sha256 "b99ec7ad95c917ba2087ee514119a8a51929b8cb0bff9158645739bc3a5632b0"
  end

  def install
    bin.install "splicectl"
  end

  test do
    system "#{bin}/splicectl --help"
  end
end
